### ISSUE TITLE
Problem with linkerOptions and duplicated symbol 

### ISSUE THREAD

**Issue by selimanac** [sharkhack/ShareWithInstagram#1]
Hi,

First of all thanx a lot for that ane. But i need some help....

I am having the error below...  
I have iOS 7.1 sdk so  ios-platformoptions.xml having problem with "L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.0.sdk/usr/lib" 

Also i am using this ane: https://github.com/freshplanet/ANE-ImagePicker. 
I dont understand why but looks like something is duplicated.

Regards, 

---

ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.0.sdk/usr/lib'
duplicate symbol _AirIPCtx in:
    /var/folders/0l/c5tqz4h968l62dm97bnd9v5c0000gn/T/0311a619-c2e5-45c8-bd25-3999dbc6ef3c/libcom.azer.ios.instagram.a(ShareWithInstagram.o)
    /var/folders/0l/c5tqz4h968l62dm97bnd9v5c0000gn/T/64ecab7c-02ae-4d3a-8fdc-e8d3357dde7e/libcom.freshplanet.AirImagePicker.a(AirImagePicker.o)
ld: 1 duplicate symbol for architecture armv7
Compilation failed while executing : ld64

**Comment by sharkhack** [comment]
Hi,
Do you need to re-compile?
Which Adobe Air version you using?

**Comment by selimanac** [comment]
No, i dont need to re-compile. Just add the ane to my project and try to compile air app. Using Air sdk 4.0, ios sdk 7.1. It gives me an that error. Looks like there is a ios sdk path problem because of the versions(you are using 7.0)

**Comment by sharkhack** [comment]
I sent the new commit. Could you try?

**Comment by selimanac** [comment]
sure

**Comment by selimanac** [comment]
It works now. StatusEvent trace = [StatusEvent type="status" bubbles=false cancelable=false eventPhase=2 code="INSTAGRAM" level="OK"] 

But nothing happens. Did i miss something?

**Comment by sharkhack** [comment]
You should check the ByteArray is correct... (if you use bitmapdata.encode function and JPEGEncoderOptions, you set Flex Compiler additional arguments -swf-version=23)
if( isInstagramInstalled() == true){
   var bitmapdata:BitmapData = new BitmapData(616,616,false,0xFFFFFF);
   var byte:ByteArray = new ByteArray();
    byte=bitmapdata.encode(bitmapdata.rect, new JPEGEncoderOptions(90), byte);
    postToInstagram(byte, "Test");
}

and than, open native application chooser keywindow.

**Comment by selimanac** [comment]
This is my test code(almost same) http://pastebin.mozilla.org/4744053 
postToInstagram  is not avaible so i use "shareWithInstagram"

**Comment by sharkhack** [comment]
I tried this way http://pastebin.mozilla.org/4744104

**Comment by selimanac** [comment]
I tried your code but nothing happens. Status event returns = [StatusEvent type="status" bubbles=false cancelable=false eventPhase=2 code="INSTAGRAM" level="OK"] . It isnt open the native instagram app.. Maybe i am missing something else...

**Comment by sharkhack** [comment]
Okay,
Half an hour after I will send the test application. 'll let you know.

**Comment by sharkhack** [comment]
ok I commit test app and new compiled .ane file. (i changed arc standart. i use standart architecture xcode)

**Comment by selimanac** [comment]
Yep, it worked. Thanks.
 Strange but it is not working when the usb debug mode activated. It work fine without the debug.
