### ISSUE TITLE
Error: Requested extension com.azer.ios.instagram is not supported for MacOS-x86.

### ISSUE THREAD

**Issue by alamboley** [sharkhack/ShareWithInstagram#2]
Hey, thanks for this ANE it works great for me on mobile.

But On Mac :
The content cannot be loaded because there was a problem loading an extension: Error: Requested extension com.azer.ios.instagram is not supported for MacOS-x86.

Would it be possible to add a default implementation (like Milkman & distriqt's one, basically doing nothing) just to not be bother by the compiler? At this time I don't know how to continue to test my app on Desktop without commenting all your ANE stuff.

Also that would be wonderful to have this one & the Android one merged into one ANE!

**Comment by sharkhack** [comment]
Hey, 
"-platform default commit" will not problem if test application on desktop...
but ShareWithInstagram only works in IOS...
if you want android, you add android ANE . the android project link: https://github.com/sharkhack/ShareWithInstagramAndroid

**Comment by alamboley** [comment]
Thanks for the quick answer.

What do you mean by "-platform default commit"? Note that I'm using FDT.

Yes, I notice Android's ANE. However it would be better to not have to fight with package & different API ;)

**Comment by sharkhack** [comment]
default mean; you can run your application on desktop...
Why my separation; which platform will you send, other platform's ane can you remove in package contents... (You can add the ane file to the application of both)
